compile:
	g++ main.cpp

run1:
	g++ main.cpp
	./a.out top24.txt ARPANET_100.txt routingTable.txt forwardingTable.txt paths.txt dist 1

run2:
	g++ main.cpp
	./a.out top14.txt NSFNET_100.txt routingTable.txt forwardingTable.txt paths.txt hop 0